service: gasmon # NOTE: update this with your service name

provider:
  name: aws
  deploymentBucket: net.clifflu.sls-deploy.${self:provider.region}
  runtime: nodejs4.3
  region: us-west-2
  memorySize: 128
  timeout: 10

functions:
  gasmon:
    handler: handler.gasmon
    events:
      - schedule: "cron(0 */12 ? * SAT,SUN *)"

#    Define function environment variables here
#    environment:
#      variable2: value2
